services:
  - type: web
    name: google-shopping-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SERPAPI_KEY
        sync: false 