services:
  - type: web
    name: product-search
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: OXYLABS_USERNAME
        sync: false
      - key: OXYLABS_PASSWORD
        sync: false 